### ISSUE TITLE
Please add license to this repo

### ISSUE THREAD

**Issue by jasnow** [rubyperu/ready4rails#12]
Can you please add a license to this repo?
Here is some background on licensing open source software:
http://code.tutsplus.com/tutorials/open-source-101-licensing--cms-21279

Here is another reference:
https://robots.thoughtbot.com/maintaining-open-source-projects-licenses

Are you going to support Rails 5?

**Comment by Florent2** [comment]
Just added the MIT license, thanks for the suggestion.

Yes, we are going to support Rails 5 in the coming months.

**Comment by jasnow** [comment]
Great. Willing to help contribute with Rails 5 update if you all wish. Do you expect to merge the different forks before updating?

**Comment by Florent2** [comment]
@jasnow sorry for the very late reply, and thanks for your proposal!

I've cleaned up the code base this week, there is now a single branch (`master`) that uses Rails 4.2, and the domain is now `ready4rails.net` instead of `rails4rails4.net`

Any contribution is welcome, I think that to add Rails 5 support we should:

* rename the existing columns `status` and `notes` to `status_rails4` and `notes_rails4`
* add 2 new columns `status_rails5` and `notes_rails5`
* update the gem creation form to include these 2 new columns
* same with the "Check my Gemfile" result page
* simplify the UI by removing "ready", "not ready" and "unknown" filters from the index page
  * optionally add a new link "download all gem infos" that downloads a CSV of all gems with statuses and notes

I plan to simplify the codebase to remove the custom caching mechanism we have, we may not need any caching mechanism, or just rely on basic HTTP caching. So if you still want to contribute, don't bother doing anything with our current custom caching mechanism.

**Comment by jasnow** [comment]
Thanks for the update
