### ISSUE TITLE
[Feature] Adding an API to search gem details.

### ISSUE THREAD

**Issue by sameera207** [rubyperu/ready4rails#16]
Hi @Florent2 ,
It would be great to have an API to check the availability of the gems. In my company we are doing number of rails upgrades (from older versions of rails to rails4.x) . So if `ready4rails` has an api, we could write a script/gem to go through our apps `Gemfile.lock` and see if the gems are ready for rails4/5. 

My high level thinking is,

Search
-------------------
```
end point - http://www.ready4rails.net/api/ready 
request type - POST
params - gem_name <gem name>
```
response
```
response type - JSON
response - { 'gem_name' => { "rails4" => true, "rails5" => false } }
```
and also, at some point we can extend this api to feed the gem details. E.g if we have a running rails4 app, we can updated the script/gem to notify the gems used in `Gemfile.lock` to update "ready4rails". 

Let me know your thoughts, if you are happy, I could get start on this :smile: 

cheers

**Comment by Florent2** [comment]
Hi Sam!

I like the idea of having a JSON API :)

I don't see the need for a new endpoint though, what about just reusing the existing one and allow it to consume JSON requests?

`GET` `/rubygems/:gem_name` would return the JSON version of the found by name `Rubygem` record, so we would just use the standard [`respond_to`](http://api.rubyonrails.org/classes/ActionController/MimeResponds.html#method-i-respond_to) method.

We can even have an API endpoint so that you can check all the gems of a Gemfile at once, using the existing endpoint `POST /gemfile_checks` (string param `gemfile` contains the joined Gemfile lines) and allow it to also consume JSON requests.

What do you think?

Cheers

**Comment by sameera207** [comment]
Hi @Florent2 , 

Great, and I see your point :). we can plug the API to the same application end points. I was thinking more about having the API as a separate component. However I think as you said, we can start with what you proposed and see how it goes :)

Since you are happy with the idea, I think I can start this and hopefully should be able to have something ready by next week.

cheers

**Comment by sameera207** [comment]
Hi @Florent2 , I sent a PR for a basic api. 

it doesn't do much ATM, but we can use it as a starting point and evolve with time :)
